version: 2
jobs:
        build:
                docker: 
                        - image: dxh30/secret:latest
                          auth:
                                  username: dxh30
                                  password: $DOCKERHUB_PASSWORD
                steps:
                        - checkout
                        - run:
                                name: Running Make
                                command: make
        test:
                docker:
                        - image: dxh30/secret:latest
                          auth:
                                  username: dxh30
                                  password: $DOCKERHUB_PASSWORD
                steps:
                        - checkout
                        - run:
                                name : Running Make
                                command: make
                        - run:
                                name : Running Make Clean
                                command: make clean
workflow:
        version: 2
        main:
                jobs:
                        - build
                        - test
