version: 2
jobs:
        buildtest:
                docker: 
                        - image: dxh30/secret:latest
                          auth:
                                  username: dxh30
                                  password: $DOCKERHUB_PASSWORD
                steps:
                        - checkout
                        - run:
                                name: Running Make
                                command: make
workflow:
        version: 2
        main:
                jobs:
                        - buildtest
